### ISSUE TITLE
Automatic stacking and masking not running in new computer, and manual masking comes out white

### ISSUE THREAD

**Issue by pbrennan10** [evo-biomech/scAnt#11]
Hi Fabi,
I got a brand new lab computer, much bigger than the old one. Its a Dell 3660 Precision Tower intel core i9-12900K processor (30MB cache, 16 core (8P+8E), 3.2. GHz to 5.2GHz (125W) TDP, 64GB, 4x16GB, DDR5 up to 4000MHz UDIMM non-ECC memory, NVIDIA RTX A5000 16GB GPU, and I can't get the scAnt to automatically stack and mask.  I thought our previous failure to do so was because of the size of the processor in the old computer. Should we be able to do this automatically now, and maybe something else is not working? Ideas welcome. The other problem we are running into is that when we run the manual masking, the masks come out all white  (not all black like before), we have modified the threshold, the min and max threshold values, and the CLAHE (we have tried multiple values up and down). We have checked that we have the newest scripts, but so far no luck.  I am attaching a couple of the masked images here. Any thoughts or ideas would be greatly appreciated.

![_x_00230_y_00000__masked](https://user-images.githubusercontent.com/54454753/179019584-6d4a670a-3b4d-46ac-88a4-59ab34c203cd.png)
![_x_00230_y_00160__masked](https://user-images.githubusercontent.com/54454753/179019604-460feaec-15e8-4aec-a21d-f0b46eee59e4.png)

**Comment by FabianPlum** [comment]
Hi Patty!

Could you upload the original stacked images (just one or two examples to dial in the settings), as well as the parameter range you have tried so far, so I can have a look at what might be going wrong?

All the best
Fabi

**Comment by pbrennan10** [comment]
Hi Fabi,
I will do so next week! Thanks,
Patty

**Comment by pbrennan10** [comment]
Fabi! We figure out that the problem is that the stacked images have an edge to them that is being read as the contour when masking (See attached images).  To solve this, we cropped 4 images just a little bit (10 pixels or so around the edge), and re ran the masking and it worked perfectly.  The weird thing too is that when running the original stacked images, there is an additional file that is being saved called a contour, where you can see the white edge that the computer thinks is the object.  So the solution would seem to be to add a step after the stacking that crops all the pictures by 10 pixels all around. In these particular pictures we painted the white areas to increase contrast, but the problem persists.  Do you ever experience this problem? do you have a workaround? The CLAHE value we use makes no difference whatsoever... we have used everything between 4 and 11 and it always comes out the same. Below we attached one pic that worked with the original stacked images, and one that did not, and below the masks that worked after cropping.
Let me know what you think,
Patty


![_x_00150_y_00160_](https://user-images.githubusercontent.com/54454753/186209387-03a492d0-461b-4068-bb4f-898d9bbb9df2.jpg)
![_x_00150_y_00160__contour](https://user-images.githubusercontent.com/54454753/186209389-f8bfe9f4-7bef-4cea-a915-4b7a6ff68672.png)
![_x_00150_y_00160__masked](https://user-images.githubusercontent.com/54454753/186209390-5e8e8e0b-b46d-49fa-b61c-ac0f9c7964b6.png)
![_x_00150_y_00320_](https://user-images.githubusercontent.com/54454753/186209391-a7307594-a8a2-4106-baa4-d371161d83b2.jpg)
![_x_00150_y_00320__contour](https://user-images.githubusercontent.com/54454753/186209393-123f0995-f392-49c3-a928-ef029aa57bf5.png)
![_x_00150_y_00320__masked](https://user-images.githubusercontent.com/54454753/186209397-bbe51554-bbb7-4389-bbd1-b55deeecd6d4.png)
![_x_00150_y_00480_cropped](https://user-images.githubusercontent.com/54454753/186209399-e1ee86a2-1163-4474-832a-0b44fbb53928.jpg)
![_x_00150_y_00480_cropped_masked](https://user-images.githubusercontent.com/54454753/186209400-57674777-3cd7-4b4b-bbe5-6f0f9c185230.png)
