### ISSUE TITLE
Problems opening the controller window

### ISSUE THREAD

**Issue by pbrennan10** [evo-biomech/scAnt#13]
Hi Fabi,
Mysteriously, scAnt controller window is not opening in either one of my computers now...  we can still use scripts manually, like stacking and masking, but the controller widow does not open.  We don't get an error message or anything, just no window.  we tried the Liver view FLIR script and it does not open either.  We have restarted everything and the problem persists...  Would appreciate any thoughts! We can zoom if you can afford some time and you can look around to see if you can diagnose the problem.
Thanks!
Patty

**Comment by pbrennan10** [comment]
Update: Sometime it works! But we would like to figure out why it does not sometimes...

**Comment by FabianPlum** [comment]
Hi Patty!

How are things with your system?
I am now finally getting around to helping out with more scAnt requests, as we slowly ramp up developement work on that front again.

Let me know how things are on your end! I would love to see some of the models you have produced

All the best
Fabi
