### ISSUE TITLE
The issue about stepper motor

### ISSUE THREAD

**Issue by kingofmaster** [evo-biomech/scAnt#14]
Dear professor:
we are currently working on building the scAnt - 3D Insect. However, at the end of the whole project, we encountered a difficult problem.  Therefore, we holp to get your help.
We have purchased the stepper motor according to the list you provided.  But, we do not know how to debug stepper moto by Tic Control Center.  We holp to get your suggestions.

**Comment by FabianPlum** [comment]
Hi!

Could you elaborate a little regarding where exactly you get stuck? At the moment it's a little hard to pin down where your issue lies.

All the best
Fabi
