### ISSUE TITLE
Estimate Camera Positions

### ISSUE THREAD

**Issue by BeefromKorea** [evo-biomech/scAnt#15]
Hello Fabi and scAnt,

First of all, thank you so much for sharing your magnificent work with all. 
I have gladly been able to produce some superb 3d scan of insects. 

I do have a small problem, which is with the estimate_camera_position code. 
I am trying to generate a sfm file, since Zephyr 3D is having some issues with reconstructing a butterfly of mine. 

Currently, the script downloaded from scAnt website goes like this...

if __name__ == '__main__':
    config = read_config_file(path=Path.cwd().parent.joinpath("example_config.yaml"))

    generate_sfm(project_location=Path("/home/fabi/camponotus_gigas"), use_cutouts=False)

    exit()

When i try to run it (with the script within the scAnt folder ) I am immediately stuck with errors with double WW as seen below: 

![image](https://user-images.githubusercontent.com/116781044/198189981-fc2b5331-c45b-4da9-8d76-0f9ba310ff21.png)

I just did not quite understand why double // kept cropping up with path...
Since I am not a great pythoner, I tried to by-pass this error by hardcoding the path e.g. 

    config = read_config_file(path="C:\scAnt\config.yaml")

    generate_sfm(project_location=Path("C:\scAnt\Butterfly"), use_cutouts=False)

    exit()

which gave me other errors:

![image](https://user-images.githubusercontent.com/116781044/198190720-3378899c-6336-439d-98a8-8424b4206c09.png)

This suggested that whatever I am doing is wrong. Considering all this ... would it be possible for you as to point me to the right direction in generating the sfm file?

Thanks so much
From Bee

**Comment by FabianPlum** [comment]
Hi Bee,

So glad to hear you are enjoying our work and have been 3D capturing insects with it!

The script you are using there was originally written for a (now legacy) version of Meshroom and not specifically for 3DF Zephyr. I'm in the process of picking up work on the scAnt project again to provide further functionality and iron out a few bugs.

Could you perhaps upload some of your pictures from the scan in question here so we may find a hotfix for you, while I rework some of the reconstruction scripts and perhaps build a Zephyr specific solution?

All the best
Fabi

**Comment by BeefromKorea** [comment]
Hello Fabian,

Thanks so much for the quick reply. 
This is what I have so far!

![image](https://user-images.githubusercontent.com/116781044/198501862-e3f7124d-c730-4e1d-947a-3ab261d0cea5.png)

As you can see the butterfly has a completely different pattern on the underside and with the wing being extremely thin, Zephyr is having a hard time in finding keypoints to build the bottom half of the point cloud (This is my opnion!)
Thus, the programme have decided not to use half of the photos taken, and built a point cloud only using the first 300 photos.

This brought me to the estimate_camera_position.py code since I wanted to tell Zephyr forcefully, all the camera positions and hence use all the photos. From it the program can build a more complete 3d model.

![Butterflytop](https://user-images.githubusercontent.com/116781044/198509554-6fcd82c2-1b87-4b16-8d3d-bed674efbd9d.jpg)

![Butterflybot](https://user-images.githubusercontent.com/116781044/198509626-808fd54f-45e0-4404-9db2-4dd847f55dae.jpg)

I have attached two butterfly photos but please let me know if you need more. I have yet to try building butterfly with meshroom, if I do have time then I will try and share the outcome.

Also, you don't need to hurry and give me a hot fix! An estimate_camera_position for Zephyr would be immaculate but even without it, I am really grateful and appreciate your passion for sharing knowledge :)

I am also in the midst of improving the current setup with (either a macro lens or a better lens then V3522-MPZ) and if it helps you and the community, then I will try and share the experience.

Thanks so much
From Bee

**Comment by FabianPlum** [comment]
Hi Bee,

How have you been? 
We are now continuing work on the scAnt project and will add new and updated scripts for more straightforward post processing on both the stacking and masking front. 

Have you reconstructed any insects in full in the meantime? Would love to hear more about your insights and experience with scAnt so far and which additions you would like to see!

All the best
Fabi

**Comment by FabianPlum** [comment]
Oh @BeefromKorea :

I would love to see your assembled scanner! Would you mind sharing some pictures of it with me, so we can add you to our growing world map of scAnt builds?

All the best
Fabi

**Comment by BeefromKorea** [comment]
Hello Fabian, 

Sorry for the delayed reply. It's been almost two month. Our lab has been extremely busy lately, but things have finally settled. 
Yes, we would love to upload our scanner. We are currently repairing the x-axis motor, once that's been sorted, we would certainly upload our scanner photos as well as some insect 3D models. 

As for our scanning experience, the scAnt side has been perfect, thanks to you! But we are struggling on the meshing side with Zephyr 3DF. I am suspecting that might be the reason why you chose to post-process the models in Blender :)

The progress has been painfully slow, but we are progressing and I hope all goes well for you also Fabian :)

Thanks
From Bee
