### ISSUE TITLE
Potential causes for automatic stacks and masks not generating during scan

### ISSUE THREAD

**Issue by Beamsspam** [evo-biomech/scAnt#18]
Hello, my apologies for disturbing you, however I am encountering an issue wherein it doesn't appear that the stacks or masks are generating automatically during the operation of the scanner despite having checked the boxes to do so in the GUI. I am currently using a digiCamControl on Windows 11 to perform the scans with a Nikon D7500 camera. Are there any potential points I should investigate first when trying to determine the cause so I can correct it?

**Comment by msheps03** [comment]
I ran into a similar issue when the destination folder contained spaces (ex. "Blue Bee"). By renaming the destination folder to be a single string it solved that issue for me (ex. "Blue_Bee"). Hope this helps.
