### ISSUE TITLE
Stacking and masking scripts not fully work via GUI anymore

### ISSUE THREAD

**Issue by henrikmyl** [evo-biomech/scAnt#4]
Stacking and masking scripts not fully work via GUI anymore. 

I have done several test scanning (using latest software versions) and every time i get all raw images, but after 5 - 40 stacking and masking images rest of these images remain uncreated. Is this results in some kind of memory leak??

Now when scanning is done and axis go back to homes, these scripts also stop. In an earlier scAnt version these scripts stopped after the images were completed.

This is not big deal for me, i can also run these scripts separately as instructed. This may make the process a little faster...

Software

scAnt 1.2
Anaconda Navigator 2.1.2
SpinnakerSDK_FULL_2.6.0.156_x64
spinnaker_python-2.6.0.156-cp37-cp37m-win_amd64.whl

My computer 

Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz x64
RAM 16,0 GB
GeForce RTX 3070

Free disk space over 600 GB

**Comment by FabianPlum** [comment]
Thanks for letting us know! 
Will look into this issue asap and come back with a solution

**Comment by FabianPlum** [comment]
The issue should now be fixed! After scanning is completed, stacking and masking scripts should continue to work through all queued images. Let me know if the problem persists on your side!

**Comment by FabianPlum** [comment]
Awesome! Thanks a lot for letting me know!
